### PR TITLE
RateLimitPolicy: VirtualHost level rate limit configuration

### PR DESCRIPTION
**Pull request by eguzki**
- [x]  Propose RateLimitPolicy API changes:
  * At VirtualHost level, an array of RateLimit object including `stage and action list`. Matches Envoy's [VirtualHost API](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=virtualhost)
  * At route level, an array of RateLimit object including `stage and action list`. Matches Envoy's [RouteAction API](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html?highlight=virtualhost#envoy-v3-api-msg-config-route-v3-routeaction)
- [ ]  Implementatoin of the proposed RateLimitPolicy API changes

Probably in a new PR I am planning to implement:
- [ ] Add `remote_address` action specifier.
- [ ] Add `metadata` action specifier.

### CODE REVIEW

**Comment by eguzki** [comment]
I would appreciate some review of the proposed API changes before going to implementation @rahulanand16nov

**Comment by eguzki** [comment]
Check for the changes in the RateLimitPolicy API. Are they ok for you?  Naming is ok for you?

**Comment by rahulanand16nov** [comment]
Yes, matches more with Envoy's structure.

**Comment by rahulanand16nov** [comment]
I suggest having #82 merged first and then having this PR rebased on top.

**Review by maleck13 — APPROVED** [review]
Looks good to me. Would be nice to update the samples with a concrete example

**Comment by rahulanand16nov** [comment]
#82 is merged. Feel free to add all the items on the list in this PR.

**Pull request closed without merging**
